### ISSUE TITLE
Can't find the lang

### ISSUE THREAD

**Issue by melanie-go** [xxcram/hypher-for-jQuery#11]
Hi ! 
Like I was saying, I have some issues to get the plugin to work at all.
I've included the patterns files manually and disable autoload because I don't use a Apache/NGINX server.
On load, I have this error : `Uncaught TypeError: Cannot read property 'leftmin' of undefined at new Hypher (jquery.hypher.js: 165)`
I guess it doesn't found the lang code. The HTML lang attribute is `de-DE` or `fr-FR`, these locales are in the plugin table `langCode`, so I don't understand why this is not working.
I try to call the function with and without options, no change.

Thank you for your help.
Melanie.

**Comment by mawiswiss** [comment]
I think the plugin does not find the pattern files. `de-DE` isn't working, you need to add just `de` to the `lang` option

**Comment by melanie-go** [comment]
I also tried to add `de` to the lang option but the error remains the same.
Doesn't the table `langCode` in `jquery.hypher.js`associate the locales code with the pattern file automatically ?

**Comment by mawiswiss** [comment]
You are completely right. I just checked the code (it's a long time since I've written that plugin 😉).

I just tested it. Your error is thrown when the language pattern is not available.

Have you done it this way?

```
<script src="../patterns/de.js"></script>

...

<script>
	$('p').hyphenate({
		lang: 'de-DE', // or also works in the html lang attribute
		autoload: false,
		hypenChar: true // just for testing
	});
</script>

**Comment by melanie-go** [comment]
No problem !
I tried the different ways below and also without option : 
1/
```
<script src="../patterns/de.js"></script>
<script src="jquery.hypher.js"></script>
...
<script>
	$('p').hyphenate({
		lang: 'de-DE', 
		autoload: false,
		hypenChar: true 
	});
</script>
```

2/ 
```
<script src="jquery.hypher.js"></script> // I put the plugin first
<script src="../patterns/de.js"></script>
...
<script>
	$('p').hyphenate({
		lang: 'de-DE', 
		autoload: false,
		hypenChar: true 
	});
</script>
```
3/ 
```
<script src="jquery.hypher.js"></script> // I put the plugin first
<script src="../patterns/de.js"></script>
...
<script>
	$('p').hyphenate({
		lang: 'de', 
		autoload: false,
		hypenChar: true 
	});
</script>
```

4/ 
```
<script src="../patterns/de.js"></script>
<script src="jquery.hypher.js"></script> 
...
<script>
	$('p').hyphenate({
		lang: 'de', 
		autoload: false,
		hypenChar: true 
	});
</script>
```

**Comment by mawiswiss** [comment]
All those variations work in my case. Your issue looks very strange to me.

Can you type `Hyphenator.languages` inside your console and tell me which languages are showing up?

**Comment by melanie-go** [comment]
Yes, I don't understand neither.
`Hyphenator.languages` give me an array with the `fr` language/pattern. For now I have only included `fr` et `de` patterns, but my page is in dutch (`lang="de-DE"`).

**Comment by mawiswiss** [comment]
Oh. I got it now. The pattern files are overriding each other. So the last one you include is available.

I need to fix that

**Comment by melanie-go** [comment]
Oh ok ! The last one I included is the `fr` pattern file indeed.

**Comment by mawiswiss** [comment]
I just pushed a new version of the pattern files. This should fix your error

**Comment by melanie-go** [comment]
Thank you ! I'll let you know :)

**Comment by melanie-go** [comment]
Hey ! 
It's all good ! Thank you so much !!

**Comment by mawiswiss** [comment]
Alright 👌 You're welcome. Thanks for using it
